config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create, :edit] do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, format: { with: /chinese|italian|japanese|french|belgian/ }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, :content, presence: true
  validates :rating, numericality: true, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    Restaurant.new(new_params)

    redirect_to @restaurant, notice: 'We have listsed your entry' if @restaurant.save
    render :new
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def new_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(reviews_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def reviews_params
    params.require(:review).permit([:content, :rating])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_restaurant_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category %>
    <%= f.input :phone_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<h1>BAD YELP</h1>
<ul>
<% @restaurants.each do |restaurant| %>
  <li><%=link_to restaurant.name, restaurant_path(restaurant), class: "btn btn-primary" %></li>
<% end %>
</ul>

app/views/restaurants/new.html.erb
<%= render 'restaurant_form', restaurant: @restaurant %>
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h4><%= @restaurant.category %></h4>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<hr>
<%=link_to "Write a Review ✍🏻", new_restaurant_review_path(@restaurant) %>
<h3>Reviews ⭐️</h3>
<% @restaurant.reviews.each do |review| %>
  <p><%= review.content %></p>
  <p><%=review.rating %></p>
<% end %>

app/views/reviews/_form.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/new.html.erb
<%= render 'form', review: @review %>